### ISSUE TITLE
ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (214, 320, 2)

### ISSUE THREAD

**Issue by yangt1013** [fzliu/saliency-bms#1]
Hello,thanks for sharing your coding.I meet the problems:
Traceback (most recent call last):
  File "saliency.py", line 139, in <module>
    main(args)
  File "saliency.py", line 127, in main
    img_sal = compute_saliency(img)
  File "saliency.py", line 81, in compute_saliency
    img_lab = rgb2lab(img)
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/skimage/color/colorconv.py", line 1032, in rgb2lab
    return xyz2lab(rgb2xyz(rgb), illuminant, observer)
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/skimage/color/colorconv.py", line 674, in rgb2xyz
    arr = _prepare_colorarray(rgb).copy()
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/skimage/color/colorconv.py", line 145, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (214, 320, 2)

How to solve it?
I am waiting for your reply

**Comment by fzliu** [comment]
You'll need to make sure your input image has 3 channels (R, G, and B).

**Comment by yangt1013** [comment]
I only use the images in your demo image as input

**Comment by lzx1729186127** [comment]
I have encountered the same problem, and I also use their images as input. Have you solved it now? I think it may be that the code did not handle the channel properly when processing the image, but I can't find out

**Comment by David-Ef** [comment]
A possible fix would be to replace the call to [rescale](https://github.com/fzliu/saliency-bms/blob/ebc6013beeff51f8077d2e2346204b2b09921883/saliency.py#L122) with:

```py
        scale = args.max_dim/float(upper_dim)
        img = cv2.resize(img, (0, 0), fx=scale, fy=scale)
```
